from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Role(str, Enum):
    """Role of a message in a conversation."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


@dataclass(slots=True)
class Message:
    """
    A single message in a conversation.

    This class is provider-independent and can be converted to the format
    required by OpenAI, Anthropic, HuggingFace, Ollama, etc.
    """

    role: Role
    content: str


@dataclass(slots=True)
class ToolCall:
    """
    A request from the model to execute a tool.
    """

    id: str | None
    name: str
    arguments: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class AssistantMessage(Message):
    """
    Message generated by the assistant.

    Besides plain text, it may contain one or more tool calls or tool call error.
    """

    tool_calls: list[ToolCall] = field(default_factory=list)
    tool_call_error: str | None


@dataclass(slots=True)
class ToolMessage(Message):
    tool_call_id: str


@dataclass(slots=True)
class TokenUsage:
    input: int
    output: int
    total: int


@dataclass(slots=True)
class ModelResponse:
    """
    Result returned by a language model.

    Contains both the assistant message and metadata produced during
    generation.
    """

    message: AssistantMessage
    usage: TokenUsage | None = None
    finish_reason: str | None = None
    model: str | None = None
    raw_response: Any | None = None

